# Welcome to Serverless!


service: messages # NOTE: update this with your service name

custom:
  secrets: ${file(secrets.json)}
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: false
      migrate: true
      seed: true
      convertEmptyValues: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: AashuAWS
  environment:

    MESSAGE_TABLE: messages-${opt:stage, self:provider.stage}
    EMAIL: ${self:custom.secrets.EMAIL}
    DOMAIN: ${self:custom.secrets.DOMAIN}


  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.MESSAGE_TABLE}"
    
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"


functions:
  send:
    handler: handler.send
    events:
        - http:
            path: api/v1/messages
            method: post
            cors: true

  read:
    handler: handler.read
    events:
        - http:
            path: api/v1/messages/{toEmail}
            method: get
            cors: true



resources:
  Resources:
    messageTable:
      Type: AWS::DynamoDB::Table
      Properties:
            TableName: ${self:provider.environment.MESSAGE_TABLE}
            AttributeDefinitions:
            - AttributeName: messageId
              AttributeType: S
            - AttributeName: toEmail
              AttributeType: S
            
            KeySchema:
            - AttributeName: toEmail
              KeyType: HASH
            - AttributeName: messageId
              KeyType: RANGE
            
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-dynamodb-local
  - serverless-offline
